apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: actions
    version: "1.0"
  name: actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: actions
    spec:
      containers:
      - name: actions
        image: charroux/actions:1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: actions
  name: actions
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http    
  selector:
    app: actions
  type: NodePort
status:
  loadBalancer: {}


